### ISSUE TITLE
Library works on sam architecture

### ISSUE THREAD

**Issue by wfdudley** [ndomx/MCP23017-Arduino-Library#1]
I'm using your library on an Arduino Due, which is sam architecture.
I'm using the following functions:

mcp.start();
mcp.config_bank(BANK_A, OUTPUT);
mcp.config_bank(BANK_B, OUTPUT);
mcp.digitalWrite(channel, value);

So, not "fully tested", but I wouldn't expect problems.

Thanks for the great library.
Bill Dudley

**Comment by ndomx** [comment]
Thank you for your feedback! The library doesn't use any native code and relies entirely on the `Arduino`  and `Wire` libraries. Any microcontroller that supports these libraries should be good to go.

**Comment by wfdudley** [comment]
I figured you could add "sam" to the architectures field in
library.properties so the warning will go away.

I did that on my local copy.

Thanks,
Bill Dudley

This email is free of malware because I run Linux.

**Comment by ndomx** [comment]
Solved in 
- #2
